### ISSUE TITLE
Make the fields in the search function required

### ISSUE THREAD

**Issue by 2016rshah** [2016rshah/bookshelf#13]
As of right now if you try to search for a book and leave the author blank you will get a 500 internal server error or somesuch nonsense. To fix this easily, make the search fields in the search function required.

**Comment by benwiley4000** [comment]
Hey - I'd be interested in helping out but it would be great for your to commit instructions for running your code to your readdme!

**Comment by robjloranger** [comment]
ya super lost there :) :+1:

**Comment by 2016rshah** [comment]
Sorry about that guys, I tried to clarify as much as I could! If there is anything else I need to go into detail on/explain better please let me know. 

I'm looking forward to your contributions 😃
