### ISSUE TITLE
Notify user why something went wrong

### ISSUE THREAD

**Issue by 2016rshah** [2016rshah/bookshelf#19]
As of right now, if the user enters bad input for some reason, the incorrect field will be highlighted in red. Typically this is alright, but if the error is something not obvious, we would like to tell the user how to fix it. 

For example, ISBN numbers have to be unique so you can't enter the same book twice. Whenever you try to, the ISBN field will just be highlighted in red. Instead it would be better to actually let the user know that they already have entered that book.

**Comment by themcny** [comment]
I'll tackle this

**Comment by 2016rshah** [comment]
As mentioned in #20, I don't just want to notify the user, I also want to notify the user *nicely*

**Comment by thebradhimself** [comment]
Let me know if this works for you:  https://github.com/2016rshah/bookshelf/pull/23
