### ISSUE TITLE
Better navigation links

### ISSUE THREAD

**Issue by 2016rshah** [2016rshah/bookshelf#9]
For example, in the searching, selecting books, have navigation back to bookshelf (at the top of the page) etc.

**Comment by admir23** [comment]
hey @2016rshah ,

may I have go at this?

Thanks
Admir

**Comment by admir23** [comment]
Also, is this part of hacktoberfest?

**Comment by 2016rshah** [comment]
To be completely honest, I don't remember what I wanted out of this issue --there are already navigation links at the top of the page? I'm going to close this issue but yes I am totally looking for Hacktoberfest contributions, check out [the other issues](https://github.com/2016rshah/bookshelf/issues) I would love your help 🎃
